version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      args:
        BACKEND_URL: http://backend:8080
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/JWTSecureTFA
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: THsF*3858
    depends_on:
      - database

  database:
    image: postgres:13
    environment:
      POSTGRES_DB: JWTSecureTFA
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: THsF*3858
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

