spring:
  application:
    name: JWTAuthService
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/jwtauthserver}
    password: ${SPRING_DATASOURCE_PASSWORD:THsF*3858}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
JWTAuthService:
  secret-key: 7dec524d50d2b1ec883f422e015659b1e57e42305e84c3cabb6d70911de2bc24
